# Generated by Django 5.2 on 2026-05-14 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'carrinho', 'verbose_name_plural': 'carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'item do carrinho', 'verbose_name_plural': 'itens do carrinho'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'imagem do produto', 'verbose_name_plural': 'imagens dos produtos'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'variacao do produto', 'verbose_name_plural': 'variacoes dos produtos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Caminho da imagem em static. Ex: imagens/Blazer.webp', max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Caminho da imagem em static. Ex: imagens/Blazer.webp', max_length=255),
        ),
    ]
